OPERATIONS = {'delete_capi_v3_algoOpenOrders': {'auth': True,
                                   'body_fields': [],
                                   'method': 'DELETE',
                                   'path': '/capi/v3/algoOpenOrders',
                                   'query_fields': ['symbol'],
                                   'service': 'Trade'},
 'delete_capi_v3_algoOrder': {'auth': True,
                              'body_fields': [],
                              'method': 'DELETE',
                              'path': '/capi/v3/algoOrder',
                              'query_fields': ['orderId'],
                              'service': 'Trade'},
 'delete_capi_v3_allOpenOrders': {'auth': True,
                                  'body_fields': [],
                                  'method': 'DELETE',
                                  'path': '/capi/v3/allOpenOrders',
                                  'query_fields': ['symbol'],
                                  'service': 'Trade'},
 'delete_capi_v3_batchOrders': {'auth': True,
                                'body_fields': ['orderIdList', 'origClientOrderIdList'],
                                'method': 'DELETE',
                                'path': '/capi/v3/batchOrders',
                                'query_fields': [],
                                'service': 'Trade'},
 'delete_capi_v3_order': {'auth': True,
                          'body_fields': [],
                          'method': 'DELETE',
                          'path': '/capi/v3/order',
                          'query_fields': ['orderId', 'origClientOrderId'],
                          'service': 'Trade'},
 'get_capi_v3_account_accountConfig': {'auth': True,
                                       'body_fields': [],
                                       'method': 'GET',
                                       'path': '/capi/v3/account/accountConfig',
                                       'query_fields': [],
                                       'service': 'Account'},
 'get_capi_v3_account_balance': {'auth': True,
                                 'body_fields': [],
                                 'method': 'GET',
                                 'path': '/capi/v3/account/balance',
                                 'query_fields': [],
                                 'service': 'Account'},
 'get_capi_v3_account_commissionRate': {'auth': True,
                                        'body_fields': [],
                                        'method': 'GET',
                                        'path': '/capi/v3/account/commissionRate',
                                        'query_fields': ['symbol'],
                                        'service': 'Account'},
 'get_capi_v3_account_position_allPosition': {'auth': True,
                                              'body_fields': [],
                                              'method': 'GET',
                                              'path': '/capi/v3/account/position/allPosition',
                                              'query_fields': [],
                                              'service': 'Account'},
 'get_capi_v3_account_position_singlePosition': {'auth': True,
                                                 'body_fields': [],
                                                 'method': 'GET',
                                                 'path': '/capi/v3/account/position/singlePosition',
                                                 'query_fields': ['symbol'],
                                                 'service': 'Account'},
 'get_capi_v3_account_symbolConfig': {'auth': True,
                                      'body_fields': [],
                                      'method': 'GET',
                                      'path': '/capi/v3/account/symbolConfig',
                                      'query_fields': ['symbol'],
                                      'service': 'Account'},
 'get_capi_v3_allAlgoOrders': {'auth': True,
                               'body_fields': [],
                               'method': 'GET',
                               'path': '/capi/v3/allAlgoOrders',
                               'query_fields': ['symbol', 'startTime', 'endTime', 'limit'],
                               'service': 'Trade'},
 'get_capi_v3_market_depth': {'auth': False,
                              'body_fields': [],
                              'method': 'GET',
                              'path': '/capi/v3/market/depth',
                              'query_fields': ['symbol', 'limit'],
                              'service': 'Market'},
 'get_capi_v3_market_exchangeInfo': {'auth': False,
                                     'body_fields': [],
                                     'method': 'GET',
                                     'path': '/capi/v3/market/exchangeInfo',
                                     'query_fields': ['symbol'],
                                     'service': 'Market'},
 'get_capi_v3_market_fundingRate': {'auth': False,
                                    'body_fields': [],
                                    'method': 'GET',
                                    'path': '/capi/v3/market/fundingRate',
                                    'query_fields': ['symbol', 'startTime', 'endTime', 'limit'],
                                    'service': 'Market'},
 'get_capi_v3_market_historyKlines': {'auth': False,
                                      'body_fields': [],
                                      'method': 'GET',
                                      'path': '/capi/v3/market/historyKlines',
                                      'query_fields': ['symbol',
                                                       'interval',
                                                       'startTime',
                                                       'endTime',
                                                       'limit',
                                                       'priceType'],
                                      'service': 'Market'},
 'get_capi_v3_market_indexPriceKlines': {'auth': False,
                                         'body_fields': [],
                                         'method': 'GET',
                                         'path': '/capi/v3/market/indexPriceKlines',
                                         'query_fields': ['symbol', 'interval', 'limit'],
                                         'service': 'Market'},
 'get_capi_v3_market_klines': {'auth': False,
                               'body_fields': [],
                               'method': 'GET',
                               'path': '/capi/v3/market/klines',
                               'query_fields': ['symbol', 'interval', 'limit'],
                               'service': 'Market'},
 'get_capi_v3_market_markPriceKlines': {'auth': False,
                                        'body_fields': [],
                                        'method': 'GET',
                                        'path': '/capi/v3/market/markPriceKlines',
                                        'query_fields': ['symbol', 'interval', 'limit'],
                                        'service': 'Market'},
 'get_capi_v3_market_openInterest': {'auth': False,
                                     'body_fields': [],
                                     'method': 'GET',
                                     'path': '/capi/v3/market/openInterest',
                                     'query_fields': ['symbol'],
                                     'service': 'Market'},
 'get_capi_v3_market_premiumIndex': {'auth': False,
                                     'body_fields': [],
                                     'method': 'GET',
                                     'path': '/capi/v3/market/premiumIndex',
                                     'query_fields': ['symbol'],
                                     'service': 'Market'},
 'get_capi_v3_market_symbolPrice': {'auth': False,
                                    'body_fields': [],
                                    'method': 'GET',
                                    'path': '/capi/v3/market/symbolPrice',
                                    'query_fields': ['symbol', 'priceType'],
                                    'service': 'Market'},
 'get_capi_v3_market_ticker_24hr': {'auth': False,
                                    'body_fields': [],
                                    'method': 'GET',
                                    'path': '/capi/v3/market/ticker/24hr',
                                    'query_fields': ['symbol'],
                                    'service': 'Market'},
 'get_capi_v3_market_ticker_bookTicker': {'auth': False,
                                          'body_fields': [],
                                          'method': 'GET',
                                          'path': '/capi/v3/market/ticker/bookTicker',
                                          'query_fields': ['symbol'],
                                          'service': 'Market'},
 'get_capi_v3_market_time': {'auth': False,
                             'body_fields': [],
                             'method': 'GET',
                             'path': '/capi/v3/market/time',
                             'query_fields': [],
                             'service': 'Market'},
 'get_capi_v3_market_trades': {'auth': False,
                               'body_fields': [],
                               'method': 'GET',
                               'path': '/capi/v3/market/trades',
                               'query_fields': ['symbol', 'limit'],
                               'service': 'Market'},
 'get_capi_v3_openAlgoOrders': {'auth': True,
                                'body_fields': [],
                                'method': 'GET',
                                'path': '/capi/v3/openAlgoOrders',
                                'query_fields': ['symbol', 'startTime', 'endTime', 'page', 'limit'],
                                'service': 'Trade'},
 'get_capi_v3_openOrders': {'auth': True,
                            'body_fields': [],
                            'method': 'GET',
                            'path': '/capi/v3/openOrders',
                            'query_fields': ['symbol', 'orderId', 'startTime', 'endTime', 'limit', 'page'],
                            'service': 'Trade'},
 'get_capi_v3_order': {'auth': True,
                       'body_fields': [],
                       'method': 'GET',
                       'path': '/capi/v3/order',
                       'query_fields': ['orderId'],
                       'service': 'Trade'},
 'get_capi_v3_order_history': {'auth': True,
                               'body_fields': [],
                               'method': 'GET',
                               'path': '/capi/v3/order/history',
                               'query_fields': ['symbol', 'limit', 'startTime', 'endTime', 'page'],
                               'service': 'Trade'},
 'get_capi_v3_userTrades': {'auth': True,
                            'body_fields': [],
                            'method': 'GET',
                            'path': '/capi/v3/userTrades',
                            'query_fields': ['symbol', 'orderId', 'startTime', 'endTime', 'limit'],
                            'service': 'Trade'},
 'post_capi_v3_account_income': {'auth': True,
                                 'body_fields': ['asset', 'symbol', 'incomeType', 'startTime', 'endTime', 'limit'],
                                 'method': 'POST',
                                 'path': '/capi/v3/account/income',
                                 'query_fields': [],
                                 'service': 'Account'},
 'post_capi_v3_account_leverage': {'auth': True,
                                   'body_fields': ['symbol',
                                                   'marginType',
                                                   'crossLeverage',
                                                   'isolatedLongLeverage',
                                                   'isolatedShortLeverage'],
                                   'method': 'POST',
                                   'path': '/capi/v3/account/leverage',
                                   'query_fields': [],
                                   'service': 'Account'},
 'post_capi_v3_account_marginType': {'auth': True,
                                     'body_fields': ['symbol', 'marginType', 'separatedType'],
                                     'method': 'POST',
                                     'path': '/capi/v3/account/marginType',
                                     'query_fields': [],
                                     'service': 'Account'},
 'post_capi_v3_account_modifyAutoAppendMargin': {'auth': True,
                                                 'body_fields': ['positionId', 'autoAppendMargin'],
                                                 'method': 'POST',
                                                 'path': '/capi/v3/account/modifyAutoAppendMargin',
                                                 'query_fields': [],
                                                 'service': 'Account'},
 'post_capi_v3_account_positionMargin': {'auth': True,
                                         'body_fields': ['isolatedPositionId', 'amount', 'type'],
                                         'method': 'POST',
                                         'path': '/capi/v3/account/positionMargin',
                                         'query_fields': [],
                                         'service': 'Account'},
 'post_capi_v3_algoOrder': {'auth': True,
                            'body_fields': ['symbol',
                                            'side',
                                            'positionSide',
                                            'type',
                                            'quantity',
                                            'price',
                                            'triggerPrice',
                                            'clientAlgoId',
                                            'presetTakeProfitPrice',
                                            'presetStopLossPrice',
                                            'TpWorkingType',
                                            'SlWorkingType'],
                            'method': 'POST',
                            'path': '/capi/v3/algoOrder',
                            'query_fields': [],
                            'service': 'Trade'},
 'post_capi_v3_closePositions': {'auth': True,
                                 'body_fields': ['symbol'],
                                 'method': 'POST',
                                 'path': '/capi/v3/closePositions',
                                 'query_fields': [],
                                 'service': 'Trade'},
 'post_capi_v3_modifyTpSlOrder': {'auth': True,
                                  'body_fields': ['orderId', 'triggerPrice', 'executePrice', 'triggerPriceType'],
                                  'method': 'POST',
                                  'path': '/capi/v3/modifyTpSlOrder',
                                  'query_fields': [],
                                  'service': 'Trade'},
 'post_capi_v3_order': {'auth': True,
                        'body_fields': ['symbol',
                                        'side',
                                        'positionSide',
                                        'type',
                                        'timeInForce',
                                        'quantity',
                                        'price',
                                        'newClientOrderId',
                                        'tpTriggerPrice',
                                        'slTriggerPrice',
                                        'TpWorkingType',
                                        'SlWorkingType'],
                        'method': 'POST',
                        'path': '/capi/v3/order',
                        'query_fields': [],
                        'service': 'Trade'},
 'post_capi_v3_placeTpSlOrder': {'auth': True,
                                 'body_fields': ['symbol',
                                                 'clientAlgoId',
                                                 'planType',
                                                 'triggerPrice',
                                                 'executePrice',
                                                 'quantity',
                                                 'positionSide',
                                                 'triggerPriceType'],
                                 'method': 'POST',
                                 'path': '/capi/v3/placeTpSlOrder',
                                 'query_fields': [],
                                 'service': 'Trade'}}
