OPERATIONS = {'cancelBatchOrders': {'auth': True,
                       'body_fields': ['symbol', 'orderIds', 'origClientOrderIds'],
                       'method': 'DELETE',
                       'path': '/api/v3/order/batch',
                       'query_fields': [],
                       'service': 'Trade'},
 'cancelOpenOrders': {'auth': True,
                      'body_fields': [],
                      'method': 'DELETE',
                      'path': '/api/v3/openOrders',
                      'query_fields': ['symbol'],
                      'service': 'Trade'},
 'cancelOrder': {'auth': True,
                 'body_fields': [],
                 'method': 'DELETE',
                 'path': '/api/v3/order',
                 'query_fields': ['symbol', 'orderId', 'origClientOrderId'],
                 'service': 'Trade'},
 'getAccountBalance': {'auth': True,
                       'body_fields': [],
                       'method': 'GET',
                       'path': '/api/v3/account/',
                       'query_fields': [],
                       'service': 'Account'},
 'getAffiliateAssets': {'auth': True,
                        'body_fields': [],
                        'method': 'GET',
                        'path': '/api/v3/agency/getAssert',
                        'query_fields': ['userId', 'startTime', 'endTime'],
                        'service': 'Rebate'},
 'getAffiliateCommission': {'auth': True,
                            'body_fields': [],
                            'method': 'GET',
                            'path': '/api/v3/rebate/affiliate/getAffiliateCommission',
                            'query_fields': ['uid', 'startTime', 'endTime', 'coin', 'productType', 'page', 'pageSize'],
                            'service': 'Rebate'},
 'getAffiliateDealData': {'auth': True,
                          'body_fields': [],
                          'method': 'GET',
                          'path': '/api/v3/agency/getDealData',
                          'query_fields': ['userIds', 'startTime', 'endTime'],
                          'service': 'Rebate'},
 'getAffiliateUIDs': {'auth': True,
                      'body_fields': [],
                      'method': 'GET',
                      'path': '/api/v3/rebate/affiliate/getAffiliateUIDs',
                      'query_fields': ['uid', 'startTime', 'endTime', 'page', 'pageSize'],
                      'service': 'Rebate'},
 'getAllOrders': {'auth': True,
                  'body_fields': [],
                  'method': 'GET',
                  'path': '/api/v3/allOrders',
                  'query_fields': ['symbol', 'startTime', 'endTime', 'limit', 'page'],
                  'service': 'Trade'},
 'getBillRecords': {'auth': True,
                    'body_fields': ['coinId', 'bizType', 'after', 'before', 'limit'],
                    'method': 'POST',
                    'path': '/api/v3/account/bills',
                    'query_fields': [],
                    'service': 'Account'},
 'getBookTicker': {'auth': False,
                   'body_fields': [],
                   'method': 'GET',
                   'path': '/api/v3/market/ticker/bookTicker',
                   'query_fields': ['symbol', 'symbols'],
                   'service': 'Market'},
 'getChannelUserTradeAndAsset': {'auth': True,
                                 'body_fields': [],
                                 'method': 'GET',
                                 'path': '/api/v3/rebate/affiliate/getChannelUserTradeAndAsset',
                                 'query_fields': ['uid', 'startTime', 'endTime', 'page', 'pageSize'],
                                 'service': 'Rebate'},
 'getCoins': {'auth': False,
              'body_fields': [],
              'method': 'GET',
              'path': '/api/v3/coins',
              'query_fields': [],
              'service': 'General'},
 'getDepth': {'auth': False,
              'body_fields': [],
              'method': 'GET',
              'path': '/api/v3/market/depth',
              'query_fields': ['symbol', 'limit'],
              'service': 'Market'},
 'getExchangeInfo': {'auth': False,
                     'body_fields': [],
                     'method': 'GET',
                     'path': '/api/v3/exchangeInfo',
                     'query_fields': ['symbol', 'symbols', 'symbolStatus'],
                     'service': 'General'},
 'getFundingBillRecords': {'auth': True,
                           'body_fields': ['coinId', 'bizType', 'startTime', 'endTime', 'pageIndex', 'pageSize'],
                           'method': 'POST',
                           'path': '/api/v3/account/fundingBills',
                           'query_fields': [],
                           'service': 'Account'},
 'getInternalWithdrawalStatus': {'auth': True,
                                 'body_fields': [],
                                 'method': 'GET',
                                 'path': '/api/v3/rebate/affiliate/getInternalWithdrawalStatus',
                                 'query_fields': ['withdrawID',
                                                  'coin',
                                                  'startTime',
                                                  'endTime',
                                                  'fromAccountType',
                                                  'toAccountType',
                                                  'page',
                                                  'pageSize'],
                                 'service': 'Rebate'},
 'getKlines': {'auth': False,
               'body_fields': [],
               'method': 'GET',
               'path': '/api/v3/market/klines',
               'query_fields': ['symbol', 'interval'],
               'service': 'Market'},
 'getMyTrades': {'auth': True,
                 'body_fields': [],
                 'method': 'GET',
                 'path': '/api/v3/myTrades',
                 'query_fields': ['symbol', 'orderId', 'startTime', 'endTime', 'limit'],
                 'service': 'Trade'},
 'getOpenOrders': {'auth': True,
                   'body_fields': [],
                   'method': 'GET',
                   'path': '/api/v3/openOrders',
                   'query_fields': ['symbol'],
                   'service': 'Trade'},
 'getOrder': {'auth': True,
              'body_fields': [],
              'method': 'GET',
              'path': '/api/v3/order',
              'query_fields': ['orderId', 'origClientOrderId'],
              'service': 'Trade'},
 'getRecentTrades': {'auth': False,
                     'body_fields': [],
                     'method': 'GET',
                     'path': '/api/v3/market/trades',
                     'query_fields': ['symbol', 'limit'],
                     'service': 'Market'},
 'getServerTime': {'auth': False,
                   'body_fields': [],
                   'method': 'GET',
                   'path': '/api/v3/time',
                   'query_fields': [],
                   'service': 'General'},
 'getTicker24Hr': {'auth': False,
                   'body_fields': [],
                   'method': 'GET',
                   'path': '/api/v3/market/ticker/24hr',
                   'query_fields': ['symbol', 'symbols'],
                   'service': 'Market'},
 'getTickerPrice': {'auth': False,
                    'body_fields': [],
                    'method': 'GET',
                    'path': '/api/v3/market/ticker/price',
                    'query_fields': ['symbol', 'symbols'],
                    'service': 'Market'},
 'getTransferRecords': {'auth': True,
                        'body_fields': [],
                        'method': 'GET',
                        'path': '/api/v3/account/transferRecords',
                        'query_fields': ['coinId', 'fromType', 'limit', 'after', 'before'],
                        'service': 'Account'},
 'internalWithdrawal': {'auth': True,
                        'body_fields': ['toUserId', 'coin', 'amount', 'fromAccountType', 'toAccountType'],
                        'method': 'POST',
                        'path': '/api/v3/rebate/affiliate/internalWithdrawal',
                        'query_fields': [],
                        'service': 'Rebate'},
 'ping': {'auth': False,
          'body_fields': [],
          'method': 'GET',
          'path': '/api/v3/ping',
          'query_fields': [],
          'service': 'General'},
 'placeOrder': {'auth': True,
                'body_fields': ['symbol', 'side', 'type', 'timeInForce', 'quantity', 'price', 'newClientOrderId'],
                'method': 'POST',
                'path': '/api/v3/order',
                'query_fields': [],
                'service': 'Trade'},
 'querySubChannelTransactions': {'auth': True,
                                 'body_fields': ['subUid',
                                                 'startTime',
                                                 'endTime',
                                                 'productType',
                                                 'pageNum',
                                                 'pageSize'],
                                 'method': 'POST',
                                 'path': '/api/v3/rebate/affiliate/querySubChannelTransactions',
                                 'query_fields': [],
                                 'service': 'Rebate'},
 'verifyReferrals': {'auth': True,
                     'body_fields': [],
                     'method': 'GET',
                     'path': '/api/v3/agency/verifyReferrals',
                     'query_fields': ['userIds'],
                     'service': 'Rebate'}}
